[semantic_release]
version_variable = "src/VERSION:0"
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = ""
commit_parser = "conventional"
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
dist_path = ["build/cslo", "build/cslod"]

[semantic_release.branches.main]
match = "main"
prerelease = false

[semantic_release.branches.other]
match = ".*"
prerelease = true
prerelease_token = "b"

[semantic_release.commit_parser_options]
allowed_tags = [
    "chore", "ci", "docs", "feat", "fix",
    "perf", "style", "refactor", "test"
]
major_tags = ["refactor"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf", "ci", "test", "chore", "docs", "style", "test"]
